# Generated by Django 5.2.1 on 2025-06-08 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=1)),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('morphology', models.CharField(blank=True, choices=[('rectangle', 'Rectangle'), ('pyramid', 'Pyramid'), ('oval', 'Oval'), ('hourglass', 'Hourglass'), ('round', 'Round')], max_length=20, null=True)),
                ('preferred_styles', models.TextField(help_text='Enter styles separated by commas (e.g., casual, elegant, minimalist)')),
                ('preferred_colors', models.TextField(help_text='Enter colors separated by commas (e.g., black, beige, navy)')),
                ('avoid_colors', models.TextField(blank=True, help_text='Enter colors to avoid, separated by commas (e.g., White, beige, yellow)')),
                ('cultural_constraints', models.TextField(blank=True, help_text='E.g., no short clothing, wearing a veil')),
                ('size_top', models.CharField(choices=[('34', '34 (XS)'), ('36', '36 (S)'), ('38', '38 (M)'), ('40', '40 (L)'), ('42', '42 (XL)'), ('44', '44 (XXL)'), ('46', '46 (XXL)')], help_text='Select your usual letter size for the top of your body', max_length=3)),
                ('size_bottom', models.CharField(choices=[('34', '34 (XS)'), ('36', '36 (S)'), ('38', '38 (M)'), ('40', '40 (L)'), ('42', '42 (XL)'), ('44', '44 (XXL)'), ('46', '46 (XXL)')], help_text='Select your usual letter size for the bottom of your body', max_length=3)),
                ('allergies', models.TextField(blank=True, help_text='List any materials to avoid, separated by commas (e.g., "laine, polyester")')),
                ('style_objectives', models.TextField(blank=True, help_text='List your style objectives, separated by commas (e.g., "paraître plus pro, oser la couleur")')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='user.outfit')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Give a name or short description for this clothing item (e.g., Blue Denim Jacket).', max_length=100, null=True)),
                ('image', models.ImageField(upload_to='wordrobe_pics/')),
                ('type', models.CharField(help_text='Enter the type of clothing shown in the picture you are providing (e.g., pants, shirt, dress, etc.).', max_length=50)),
                ('color', models.CharField(help_text='Enter the color of clothing shown in the picture you are providing (e.g., black, red, etc.)', max_length=50)),
                ('material', models.CharField(help_text='Enter the material of the clothing item (e.g., cotton, leather, wool)', max_length=100)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], help_text='Select the season this clothing is suitable for (e.g., Summer, Winter).', max_length=10, null=True)),
                ('occasion', models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('sport', 'Sport'), ('party', 'Party'), ('work', 'Work'), ('other', 'Other')], help_text='Select the occasion this clothing is typically used for (e.g., casual, formal, sport).', max_length=10, null=True)),
                ('cut', models.CharField(choices=[('slim', 'Slim'), ('regular', 'Regular'), ('oversize', 'Oversize'), ('relaxed', 'Relaxed'), ('fitted', 'Fitted')], help_text='Select the cut (fit) of the clothing item, such as slim, regular, or oversize.', max_length=10)),
                ('size', models.CharField(choices=[('34', '34 (XS)'), ('36', '36 (S)'), ('38', '38 (M)'), ('40', '40 (L)'), ('42', '42 (XL)'), ('44', '44 (XXL)'), ('46', '46 (XXL)')], help_text='Select the size of the clothing item (e.g., S, M, L, 38, 40).', max_length=3)),
                ('brand', models.CharField(blank=True, help_text='Specify the brand of the clothing item, if known.', max_length=100, null=True)),
                ('style_tags', models.TextField(help_text='Enter style tags separated by commas (e.g., minimalist, streetwear, vintage).')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.BooleanField(default=False, help_text='Mark this item as a favorite.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to='user.profile')),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='items',
            field=models.ManyToManyField(related_name='outfits', to='user.wardrobeitem'),
        ),
    ]
